
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

import os
current_dir = os.path.dirname(os.path.abspath(__file__))

ASSETS_PATH = os.path.join(current_dir, "assets", "pycache")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("500x850")
window.configure(bg = "#383838")


canvas = Canvas(
    window,
    bg = "#383838",
    height = 850,
    width = 500,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    498.0,
    -1.99932861328125,
    500.0,
    850.0013427734375,
    fill="#01D119",
    outline="")

canvas.create_rectangle(
    -1.1368683772161603e-13,
    -2.0,
    2.0,
    850.0,
    fill="#01D119",
    outline="")

canvas.create_rectangle(
    -2.0,
    0.125,
    500.0,
    2.125,
    fill="#01D119",
    outline="")

canvas.create_text(
    12.0,
    5.3125,
    anchor="nw",
    text="Settings",
    fill="#01D119",
    font=("Inter", 24 * -1)
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    479.0,
    21.1875,
    image=image_image_1
)

canvas.create_rectangle(
    -2.0,
    40.5,
    500.0,
    42.5,
    fill="#01D119",
    outline="")

canvas.create_rectangle(
    -2.0,
    848.0,
    500.0,
    850.0,
    fill="#01D119",
    outline="")

canvas.create_text(
    14.0,
    61.0,
    anchor="nw",
    text="The _pycache_ directory is used by Python to\nstore compiled bytecode files, which help speed\nup the program execution. Would you like the\nprogram to automatically delete the _pycache_\ndirectory on startup?",
    fill="#FFFFFF",
    font=("Inter", 22 * -1)
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    251.0,
    318.3125,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    250.0,
    537.5,
    image=image_image_3
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    249.0,
    701.0,
    image=image_image_4
)

canvas.create_text(
    114.0,
    447.4375,
    anchor="nw",
    text="A bit slower startup time as \nPython will need to recompile\nbytecode files\n\nMay not be necessary in \nproduction environments where \nstability is prioritized",
    fill="#FFFFFF",
    font=("Inter", 20 * -1)
)

canvas.create_text(
    23.0,
    675.8125,
    anchor="nw",
    text="We recommend to disable it to prioritize\nfaster startup times",
    fill="#FFFFFF",
    font=("Inter", 20 * -1)
)

canvas.create_text(
    107.0,
    242.25,
    anchor="nw",
    text="Ensures a clean environment by \nremoving potentially outdated or \ncorrupted files\n\nUseful during development to \navoid issues caused by stale cache",
    fill="#FFFFFF",
    font=("Inter", 20 * -1)
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    68.0,
    537.0,
    image=image_image_5
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    116.0,
    797.0,
    image=image_image_6
)

image_image_7 = PhotoImage(
    file=relative_to_assets("image_7.png"))
image_7 = canvas.create_image(
    380.0,
    797.0,
    image=image_image_7
)

canvas.create_text(
    47.0,
    778.0,
    anchor="nw",
    text="ENABLE",
    fill="#FFFFFF",
    font=("Inter", 36 * -1)
)

canvas.create_text(
    304.0,
    776.0,
    anchor="nw",
    text="DISABLE",
    fill="#FFFFFF",
    font=("Inter", 36 * -1)
)

image_image_8 = PhotoImage(
    file=relative_to_assets("image_8.png"))
image_8 = canvas.create_image(
    128.0,
    20.0,
    image=image_image_8
)

image_image_9 = PhotoImage(
    file=relative_to_assets("image_9.png"))
image_9 = canvas.create_image(
    67.0,
    320.0,
    image=image_image_9
)
window.resizable(False, False)
window.mainloop()
