templates:
  - name: "Bug Report"
    about: "Create a bug report"
    template: "bug_report.md"
  - name: "Feature Request"
    about: "Request a new feature"
    template: "feature_request.md"
  - name: "Question"
    about: "Ask a question"
    template: "question.md"