name: Add Issue to Project

description: 'Automatically adds new issues to the Collaborators Hub 👏 GitHub Project'

inputs:
  project_name:
    description: 'The name of the project to add the issue to'
    required: true
    default: 'Collaborators Hub 👏'  # Set your default project name here

runs:
  using: 'composite'
  steps:
    - name: Add Issue to Project
      id: add_issue_to_project
      uses: actions/github-script@v6
      with:
        script: |
          const issue = context.payload.issue;
          const projectName = '${{ inputs.project_name }}';

          // Fetch the repository's projects (new GitHub Projects API)
          const projects = await github.rest.projects.listForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
          });

          // Find the project by name (case-sensitive)
          const project = projects.data.find(p => p.name === projectName);

          if (!project) {
            throw new Error(`Project "${projectName}" not found.`);
          }

          // Fetch the columns for the selected project
          const columns = await github.rest.projects.listColumns({
            project_id: project.id,
          });

          if (columns.length === 0) {
            throw new Error(`No columns found for project "${projectName}".`);
          }

          // Add the issue to the first column (you can change this logic if needed)
          const columnId = columns[0].id;

          // Create a card in the selected column
          await github.rest.projects.createCard({
            column_id: columnId,
            content_id: issue.id,
            content_type: 'Issue',
          });

          console.log(`Issue #${issue.number} has been added to the project "${projectName}".`);
